apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ${{ secrets.ACR_LOGIN_SERVER }}/java-image:${{ github.sha }}
      imagePullSecrets:
      - name: acr-auth
